### ISSUE TITLE
Update Kotlin to 2.0.0

### ISSUE THREAD

**Issue by OptimumCode** [cketti/kotlin-codepoints#33]
Hello!

Could you please advise if there are any plans to update the Kotlin version to 2.0.0? I am happy to help with Kotlin update (my library depends on this one and I would prefer to have all the dependencies migrated to Kotlin 2.0.0 before I migrate my library)

Thank you!

**Comment by JakeWharton** [comment]
Using this in a library and app that are on Kotlin 2.0 without problems. Kotlin 2.0 is not incompatible with libraries built with 1.9.x. You should not have to wait for or force any of your dependencies to upgrade before you do.

**Comment by OptimumCode** [comment]
Thank you, @JakeWharton. I am aware that kotlin 2.0 works fine with libraries built using 1.9 but I like consistency in my dependencies.
I am not forcing anyone to do anything - just curious if there were plans to do the update and offered my help
