### ISSUE TITLE
Does not support 4-byte emojis

### ISSUE THREAD

**Issue by MathiasDL** [cketti/kotlin-codepoints#41]
I am looking for a method which takes the first character from a string, even if it is multibyte. For 2-byte emojis, this lib works, but not for 4-byte emojis, e.g.:
```kotlin
val length = "🇫🇷 fries".offsetByCodePoints(0, 1)
println(this.substring(0, length)) //  instead of 🇫🇷
```

Probably not something you can easily fix, because `kotlin.text.codePoints` has the same issue...

**Comment by JakeWharton** [comment]
That emoji is represented by two codepoints from the regional indicator symbol block of unicode. If you only grab one of them, you only grab "half" of the symbol.

**Comment by MathiasDL** [comment]
I guess codepoints is the wrong tool for this then, I managed to solve my issue using an additional emoji library, see https://stackoverflow.com/a/79054558/2260402

You can close this issue if you like

**Comment by JakeWharton** [comment]
It's not that they're the wrong tool, more that they don't represent what you're after. You seem to want grapheme clusters which are comprised of one or more codepoints.

I would strongly suggest renaming your function to not use the word "character" which is far too overloaded to be precise as to what its implementation is doing.

**Comment by JakeWharton** [comment]
I would also double check that library correctly supports things like 🧑‍🌾, which are actually two discrete emoji (🧑 and 🌾) with a zero-width joiner to ultimately produce a single grapheme cluster.

**Comment by MathiasDL** [comment]
It works correctly, thanks

**Comment by cketti** [comment]
Support for grapheme clusters is outside the scope for this library. The library could be used as a building block for code dealing with [text segmentation](https://www.unicode.org/reports/tr29/). But I want to keep this library focused on code point essentials.

However, if someone is building such functionality on top of `kotlin-codepoints` and discovers that changes to its API would make that job easier, I'm keen on hearing about that. In that case please open a new issue.
